#!/bin/env sh

GcovPrefix=実行された行

MakeSymlink() {
	if test ! -h "$2"; then
		ln -s $1 $2
	fi
}

PrintFormat () {
	sed -e "s/$1//g" \
	    -e "s/Creating.*\$//g" \
	    -e "s/^$GcovPrefix://g" \
	    -e "/^\$/d" \
	    -e "s/^File\s*\('[^']\+'\)$/   \1 :/g" | \
	tr '\n' ' ' | \
	sed -e 's/\(of [0-9]\+\)\s/\1\n/g'
	echo $1 | sed -e "s/$GcovPrefix:/Total : /g"
}

CheckGcov() {
	MakeSymlink ../src src
	MakeSymlink ../tests tests
	find ../objs/src -type f -name "*.gcda" -print0 | xargs -0 gcov
	rm src
	rm tests
}

main() {
	if test "-c" = "$1"; then
		rm -rf gcov
		exit
	fi

	if test ! -d gcov; then
		mkdir gcov
	fi
	make
	#if test 0 -eq $? ; then
		cd gcov
		GcovReturn=`CheckGcov`
		ResultAll=`echo "$GcovReturn" | tail -1`
		echo "--- Coverage check result ---"
		echo "$GcovReturn" | PrintFormat "$ResultAll"
	#fi
}

main $*
